name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.${project.artifactId}"
api-version: 1.19
authors: [ YouHaveTrouble ]
description: "${project.description}"
commands:
  purpurextras:
    description: Command controlling PurpurExtras
    permission: purpurextras.command
