name: PurpurExtras
version: ${project.version}
main: me.youhavetrouble.purpurextras.PurpurExtras
api-version: 1.16
authors: [ YouHaveTrouble ]
description: "\"This should be a plugin\" features from Purpur"
