name: PurpurExtras
version: ${project.version}
main: org.purpurmc.purpurextras.PurpurExtras
api-version: 1.18
authors: [ YouHaveTrouble ]
description: "\"This should be a plugin\" features from Purpur"
commands:
  purpurextras:
    description: Command controlling PurpurExtras
    permission: purpurextras.command
